//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUD_WEB_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personaprueba
    {
        public int idPersona { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string descripcion { get; set; }
    }
}
